"""baseline schema

Revision ID: 310017671d9e
Revises: 
Create Date: 2026-07-09 18:27:30.786145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '310017671d9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent', sa.Text(), nullable=False),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_tsv', 'memories', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_memories_agent'), 'memories', ['agent'], unique=False)
    op.create_index(op.f('ix_memories_project'), 'memories', ['project'], unique=False)
    op.create_index(op.f('ix_memories_timestamp'), 'memories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_memories_type'), 'memories', ['type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tags_lower_name', 'tags', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('memory_tags',
    sa.Column('memory_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', 'tag_id')
    )
    op.create_index(op.f('ix_memory_tags_tag_id'), 'memory_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_tags_tag_id'), table_name='memory_tags')
    op.drop_table('memory_tags')
    op.drop_index('idx_tags_lower_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_memories_type'), table_name='memories')
    op.drop_index(op.f('ix_memories_timestamp'), table_name='memories')
    op.drop_index(op.f('ix_memories_project'), table_name='memories')
    op.drop_index(op.f('ix_memories_agent'), table_name='memories')
    op.drop_index('idx_content_tsv', table_name='memories', postgresql_using='gin')
    op.drop_table('memories')
    # ### end Alembic commands ###
