"""Keep every review verdict: memory_reviews gets its own id.

Until now `memory_reviews` held one row per memory, and a re-review wrote
over it, so the earlier verdict was gone. That breaks the timeline rule:
nothing in this system is rewritten. From here on a re-review adds a row,
and every read shows the newest one.

- The primary key moves from `memory_id` to a new `id BIGINT GENERATED BY
  DEFAULT AS IDENTITY`. Existing rows get ids as the column is added.
- `memory_id` keeps its foreign key onto memories, ON DELETE CASCADE.
- An index on `(memory_id, created_at DESC)` finds the newest row per
  memory.

Revision ID: f4c2a8e6d1b9
Revises: e5a1c7d9f2b3
Create Date: 2026-09-29 09:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f4c2a8e6d1b9'
down_revision: Union[str, Sequence[str], None] = 'e5a1c7d9f2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Move the primary key to a new `id` column and add the index. Every
    existing row stays and gets an id."""
    op.drop_constraint('memory_reviews_pkey', 'memory_reviews', type_='primary')
    op.add_column('memory_reviews',
                  sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_primary_key('memory_reviews_pkey', 'memory_reviews', ['id'])
    op.create_index('ix_memory_reviews_memory_id_created_at', 'memory_reviews',
                    ['memory_id', sa.text('created_at DESC')], unique=False)


def downgrade() -> None:
    """Back to one row per memory: keep the newest row of each memory (by
    `created_at`, then `id`) and delete the rest, so the older verdicts are
    lost. Then drop the index and the `id` column, and make `memory_id` the
    primary key again."""
    op.execute(
        "DELETE FROM memory_reviews AS r USING memory_reviews AS n "
        "WHERE r.memory_id = n.memory_id "
        "AND (r.created_at, r.id) < (n.created_at, n.id)")
    op.drop_index('ix_memory_reviews_memory_id_created_at', table_name='memory_reviews')
    op.drop_constraint('memory_reviews_pkey', 'memory_reviews', type_='primary')
    op.drop_column('memory_reviews', 'id')
    op.create_primary_key('memory_reviews_pkey', 'memory_reviews', ['memory_id'])
