// MSW browser worker. Started from src/main.js in DEV only. The worker script
// itself (public/mockServiceWorker.js) is generated by `npx msw init public/`.
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers.js'

export const worker = setupWorker(...handlers)
